### ISSUE TITLE
Missing file when following testing instructions

### ISSUE THREAD

**Issue by AngieNicole-Hernandez** [tiryakiv/Mammogram-segmentation#1]
Hello,

I am following the Testing Instructions on this repository and I have encountered a problem. I am getting the error:
`FileNotFoundError: No such file: 'path-on-my-computer\Mammogram-segmentation-main\fgt_seg07\test\pred\0.png'`

Which arises from the line in the function testGenerator from data.py:
`img = io.imread(os.path.join(test_path,"%d.png"%i),as_gray = as_gray)`

So my question is, what is the folder that should go there? What is "0.png" supposed to be (test image, test segmentation)?

Thanks for your time.

Edit: I used the folder "segmentation_data/test/fgt_seg" and renamed the images to numbers and it worked :)

**Comment by tiryakiv** [comment]
Hello,

Sorry for the confusion. When testing, the model needs the input mammogram
images named from 0 to n-1. The test mammograms are located under
segmentation_data/test/fgt_seg. Please make sure to rename the files as
0.png 1.png ... 5.png

Best regards,
Müjdat

24 Temmuz 2023 Pazartesi tarihinde Angie Hernández ***@***.***>
yazdı:
> Hello,
>
> I am following the Testing Instructions on this repository and I have
encountered a problem. I am getting the error:
> FileNotFoundError: No such file:
'path-on-my-computer\Mammogram-segmentation-main\fgt_seg07\test\pred\0.png'
>
> Which arises from the line in the function testGenerator from data.py:
> img = io.imread(os.path.join(test_path,"%d.png"%i),as_gray = as_gray)
>
> It makes sense because I do not see the folder "fgt_seg07" on the
repository. I changed the path after "\Mammogram-segmentation-main" to
"\segmentation_data\test\fgt_seg" to see if it was supposed to be that
folder, but I still get the error
> No such file:
'path-on-my-computer\Mammogram-segmentation-main\segmentation_data\test\fgt_seg\0.png'
>
> So my question is, what is the folder that should go there? What is
"0.png" supposed to be (test image, test segmentation)?
>
> Thanks for your time.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci4.googleusercontent.com/proxy/SfMq8LqfD5ryfhxqmTqUmKVc7Lr4rvThIzul8Bp3JBcmS5G16DPIlqH205kiaLI_XURWcJtZLHR0dgeDqIRRUt9er1xnMe9cXaMv8mG3rX1dVVIccsXOYOxl9BOaa1d_sBkhMDcJeVO5Q9Mt3Q5scwaOy86GF-etzA0K4q5CARG_pvw2eF4QEICuoVIORTbNYzX9GSN8y5VS1ls25kqIZtbpEy8gL4BeVR0=s0-d-e1-ft#https://github.com/notifications/beacon/ALT2AHJBVAJAWIOIHUABKBDXRZVELA5CNFSM6AAAAAA2VRACC2WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHGYYPSBQ.gif>Message
ID: ***@***.***>

-- 
Dr. Öğretim Üyesi Volkan Müjdat TİRYAKİ
Bilgisayar Mühendisliği Bölümü
Siirt Üniversitesi Kezer Kampüsü
Siirt 56100
Email: ***@***.***
Tel: +90 484 2121111 <+90%20484%20212%2011%2011>- Dahili:3012

-------------------------------------------------

Volkan Müjdat Tiryaki, PhD
Assistant Professor
Department of Computer Engineering
Siirt University
Siirt TURKEY 56100
Email: ***@***.***
Tel: +90 484 2121111 <+90%20484%20212%2011%2011>-Ext:3012

**Comment by tiryakiv** [comment]
Example 6 test mammogram files are located under the following address:

https://github.com/tiryakiv/Mammogram-segmentation/tree/main/segmentation_data/test/fgt_seg

There are 6 test mammograms. You should download them, and rename as 0.png
, 1.png , 2.png , 3.png , 4.png, 5.png. Then you should move the six test
files under your
test path, which may look like this:

'path-on-my-computer\Mammogram-segmentation-main\fgt_seg07\test\pred\'

Do not hesitate to ask if these instructions did not help.

Müjdat

Volkan Müjdat Tiryaki ***@***.***>, 24 Tem 2023 Pzt, 18:54
tarihinde şunu yazdı:

> Hello,
>
> Sorry for the confusion. When testing, the model needs the input mammogram
> images named from 0 to n-1. The test mammograms are located under
> segmentation_data/test/fgt_seg. Please make sure to rename the files as
> 0.png 1.png ... 5.png
>
> Best regards,
> Müjdat
>
> 24 Temmuz 2023 Pazartesi tarihinde Angie Hernández <
> ***@***.***> yazdı:
> > Hello,
> >
> > I am following the Testing Instructions on this repository and I have
> encountered a problem. I am getting the error:
> > FileNotFoundError: No such file:
> 'path-on-my-computer\Mammogram-segmentation-main\fgt_seg07\test\pred\0.png'
> >
> > Which arises from the line in the function testGenerator from data.py:
> > img = io.imread(os.path.join(test_path,"%d.png"%i),as_gray = as_gray)
> >
> > It makes sense because I do not see the folder "fgt_seg07" on the
> repository. I changed the path after "\Mammogram-segmentation-main" to
> "\segmentation_data\test\fgt_seg" to see if it was supposed to be that
> folder, but I still get the error
> > No such file:
> 'path-on-my-computer\Mammogram-segmentation-main\segmentation_data\test\fgt_seg\0.png'
> >
> > So my question is, what is the folder that should go there? What is
> "0.png" supposed to be (test image, test segmentation)?
> >
> > Thanks for your time.
> >
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.<
> https://ci4.googleusercontent.com/proxy/SfMq8LqfD5ryfhxqmTqUmKVc7Lr4rvThIzul8Bp3JBcmS5G16DPIlqH205kiaLI_XURWcJtZLHR0dgeDqIRRUt9er1xnMe9cXaMv8mG3rX1dVVIccsXOYOxl9BOaa1d_sBkhMDcJeVO5Q9Mt3Q5scwaOy86GF-etzA0K4q5CARG_pvw2eF4QEICuoVIORTbNYzX9GSN8y5VS1ls25kqIZtbpEy8gL4BeVR0=s0-d-e1-ft#https://github.com/notifications/beacon/ALT2AHJBVAJAWIOIHUABKBDXRZVELA5CNFSM6AAAAAA2VRACC2WGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHGYYPSBQ.gif>Message
> ID: ***@***.***>
>
> --
> Dr. Öğretim Üyesi Volkan Müjdat TİRYAKİ
> Bilgisayar Mühendisliği Bölümü
> Siirt Üniversitesi Kezer Kampüsü
> Siirt 56100
> Email: ***@***.***
> Tel: +90 484 2121111 <+90%20484%20212%2011%2011>- Dahili:3012
>
> -------------------------------------------------
>
> Volkan Müjdat Tiryaki, PhD
> Assistant Professor
> Department of Computer Engineering
> Siirt University
> Siirt TURKEY 56100
> Email: ***@***.***
> Tel: +90 484 2121111 <+90%20484%20212%2011%2011>-Ext:3012
>
>

-- 
Dr. Öğretim Üyesi Volkan Müjdat TİRYAKİ
Bilgisayar Mühendisliği Bölümü
Siirt Üniversitesi Kezer Kampüsü
Siirt 56100
Email: ***@***.***
Tel: +90 484 2121111 <+90%20484%20212%2011%2011>- Dahili:3012

-------------------------------------------------

Volkan Müjdat Tiryaki, PhD
Assistant Professor
Department of Computer Engineering
Siirt University
Siirt TURKEY 56100
Email: ***@***.***
Tel: +90 484 2121111 <+90%20484%20212%2011%2011>-Ext:3012
